# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image_filename', models.CharField(default='', max_length=20)),
                ('author', models.CharField(default='', max_length=30)),
                ('runtime', models.CharField(default='', max_length=30)),
                ('date_published', models.CharField(default='', max_length=30)),
                ('keywords', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
