# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('publication_date', models.CharField(max_length=30)),
            ],
        ),
    ]
