# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0002_remove_podcast_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='keywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
