# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0003_podcast_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='runtime',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='podcast',
            name='upvotes',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
