# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0004_auto_20191201_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='keywords',
            field=django_mysql.models.ListCharField(models.CharField(default='', max_length=20), max_length=200, size=None),
        ),
    ]
