# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0006_auto_20191201_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='keywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
