# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0007_auto_20191201_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
    ]
